#ifndef KAPIBARA_DISTRHO_PLUGIN_INFO_H
#define KAPIBARA_DISTRHO_PLUGIN_INFO_H

#define DISTRHO_PLUGIN_BRAND "Kapibara"
#define DISTRHO_PLUGIN_NAME "Kapibara"
#define DISTRHO_PLUGIN_URI "https://local/kapibara"
#define DISTRHO_PLUGIN_CLAP_ID "local.kapibara.synth"

#define DISTRHO_PLUGIN_BRAND_ID KpBr
#define DISTRHO_PLUGIN_UNIQUE_ID Kpba

#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_IS_SYNTH 1
#define DISTRHO_PLUGIN_NUM_INPUTS 0
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 0
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 1

#define DISTRHO_UI_FILE_BROWSER 1
#define DISTRHO_UI_USER_RESIZABLE 1
#define DISTRHO_UI_USE_NANOVG 1
#define DISTRHO_UI_DEFAULT_WIDTH 1320
#define DISTRHO_UI_DEFAULT_HEIGHT 900

#endif // KAPIBARA_DISTRHO_PLUGIN_INFO_H
