    std::array<Rect, synth::kMaxWavetablePartials> partialKnobRects_ {};
    std::array<Rect, 4> sourceCountRects_ {};
    std::array<Rect, synth::kMaxSourceTracks> sourceChainRects_ {};
    Rect addTrackRect_ {};
    Rect removeTrackRect_ {};
    std::array<Rect, 4> addTrackTypeRects_ {};
    std::array<Rect, synth::kMaxSourceTracks> trackRowRects_ {};
    std::array<Rect, synth::kMaxSourceTracks> stripRects_ {};
    Rect trackOutputModeRect_ {}, trackGainRect_ {}, trackPanRect_ {}, trackSendRect_ {};
    Rect stripEnvRect_ {}, stripDupRect_ {};
    Rect ampEnvSelectRect_ {}, duplicateEnvRect_ {};
    Rect partialSpectrumRect_ {}, partialAmpRect_ {}, partialRatioRect_ {};
    Rect basicShapeRect_ {}, basicPulseRect_ {}, basicSubRect_ {};
    Rect noiseModeRect_ {}, noiseColorRect_ {};
    Rect sourceGainRect_ {}, sourcePanRect_ {}, sourceFilterEnableRect_ {}, sourceFilterTopologyRect_ {};
    Rect sourceFilterCutoffRect_ {}, sourceFilterResRect_ {}, sourceFilterDriveRect_ {}, sourceFilterFeedbackRect_ {};
    Rect sourceFilterMixRect_ {};
    Rect unisonVoicesRect_ {}, unisonDetuneRect_ {}, unisonWidthRect_ {}, unisonPhaseRect_ {};
    Rect attackRect_ {}, decayRect_ {}, sustainRect_ {}, releaseRect_ {}, curveRect_ {};
