    bool loadPathEditing_ = false;
    bool wavetableImportMenuOpen_ = false;
    bool wavetablePresetMenuOpen_ = false;
    bool droppedWavPending_ = false;
    bool presetMenuOpen_ = false;
    bool optionsMenuOpen_ = false;
    bool harmonicEditorOpen_ = false;
    bool metaProcessContextMenuOpen_ = false;
    bool routeContextMenuOpen_ = false;
    float routeContextX_ = 0.0f, routeContextY_ = 0.0f;
    int  routeContextRuleIndex_ = -1;
    std::array<Rect, 2> routeContextRects_ {};
    std::array<Rect, 2> stripRouteRects_ {};
    std::array<int,  2> stripRouteRuleIndices_ { -1, -1 };
    bool metaEditorDirty_ = false;
    MetaEditorDomain metaEditorDomain_ = MetaEditorDomain::Time;
    synth::WavetableImportMode wavetableImportMode_ = synth::WavetableImportMode::AutoDetect;
    int manualCycleLength_ = synth::kWavetableSize;
    int importFrameLimit_ = 128;
